services:
  - type: web
    name: nasir-whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.wppfrublofcbjaodoufz:CyberEagleX2026@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1
      - key: OPENROUTER_KEY
        value: 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
      - key: ADMIN_NUMBER
        sync: false
        value: 923001234567
